#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Interessengemeinschaft Hasten e.V.

# Short bio or description (displayed in the header)
description: Interessengemeinschaft Hasten e.V.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: images/logo_text_100.png

# Define pagination for blog posts etc.
paginate: 100
paginate_path: "/aktuelles/seite/:num"

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: ighasten

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-gallery-generator

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

# Options for the gallery
gallery:
  # path to the gallery
  dir: galerie
  # title for gallery index
  title: "Galerie"
  # title prefix for gallery page. title=title_prefix+gallery_name
  title_prefix: ""
  # field to control sorting of galleries for the index page
  # (possible values are: title, date_time, best_image)
  sort_field: "date_time"
  # sizes for thumbnails
  thumbnail_size:
    x: 400
    y: 400
  # custom configuration for individual gallery
  # best_image is image for the index page (defaults to last image)
  # galleries:
  #   2014-weihnachtstreff:
  #     best_image: IMG_1068.JPG
  #   japan_trip:
  #     best_image: IMG_0690.JPG
  #   best:
  #     best_image: snaileo_gonzales.jpg
